### ISSUE TITLE
xAlias on localhost without SSL

### ISSUE THREAD

**Issue by juliancwirko** [multiversx/mx-template-dapp#157]
When I use xAlias, and I'm on localhost and not using the SSL (through the Vite config), I get an unknown error when **logging out**.
I don't know where the problem is, but should we be forced to use SSL on localhost? Can we have it working also without SSL?

![Screenshot from 2023-11-01 10-06-44](https://github.com/multiversx/mx-template-dapp/assets/4427985/05070a52-b934-4d35-9b3c-ea5c960b8c8b)

**Comment by CiprianDraghici** [comment]
Hello, 
No. It's mandatory to use a secured connection (even if the env is localhost)
