### ISSUE TITLE
Proposal: Implement tailwind-merge

### ISSUE THREAD

**Issue by Enciusan** [multiversx/mx-template-dapp#176]
As this repo uses Tailwind CSS, and with the introduction of custom components, it would be beneficial to incorporate **tailwind-merge** to avoid class conflicts and simplify the process of overriding Tailwind classes. This would enhance the overall usability and maintainability of the project.

**Comment by CiprianDraghici** [comment]
While I appreciate your perspective, the template is designed with the specific goal of demonstrating the seamless integration of `@muliversx/sdk-dapp` and facilitating a more efficient developer experience with this package. It is crucial to emphasize that the incorporation of styling libraries is outside the intended scope of this context. We do not advocate for mandating the use of particular styling libraries.

Nevertheless, we value collaborative input and encourage you to share your ideas. Please consider opening a pull request (PR), and we will promptly review and consider your contributions. Your insights are highly valued.
