### ISSUE TITLE
AuthenticatedRoutesWrapper doesn't include dynamic routes

### ISSUE THREAD

**Issue by CristianFodor** [multiversx/mx-template-dapp#44]
For route paths like `path="/post/:id"` the authenticatedRoute param from routes doesn't work. 

`{
        path: "/post/:tab",
        title: "Post Details",
        component: Posts,
        authenticatedRoute: true,
}`

**Comment by StanislavSava** [comment]
UNfortunately, AuthenticatedRoutesWrapper does not support dynamic routes

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
