### ISSUE TITLE
Send transaction not working with Ledger on Address 1 and above

### ISSUE THREAD

**Issue by lukkedmm** [multiversx/mx-template-dapp#51]
It's not working to send transaction using Ledger on Address 1 and above, only on Address 0.

I tried through Webwallet and Ledger option directly on the Unlock Page and same result.

This issue has been found by many people.

The console log says "Bad request".

Any ideas how to fix this? I need a fix as soon as possible because I have a deadline and this is the last major issue I came across.

**Comment by StanislavSava** [comment]
Can you try with the latest release of dapp-core? This issue has been solved a while ago

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
