### ISSUE TITLE
Session Expired

### ISSUE THREAD

**Issue by butavpaul** [multiversx/mx-template-dapp#53]
Hello! I'm using the dapp template and sometimes if I close my browser and I'm not connected at the defi wallet and I access the dapp again, the home page is showing nothing and in the console I get some session expired errors. This also happens on the dapp template example https://dapp-template.elrond.com/
To make this work, I have to refresh the page!
I'm assuming that the dapp wants to tell me that I'm logged in, but since I've closed the browser the defi disconnects me (same for maiar app).
Are the any workarounds to solve this?
Thank you!
 
![image](https://user-images.githubusercontent.com/8864497/162560741-1616f4ea-9868-43eb-945c-9d885f40df27.png)

**Comment by StanislavSava** [comment]
can you try with dapp-core 2.0 alpha and see if the issue still persists?

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
