### ISSUE TITLE
Sender not allowed error

### ISSUE THREAD

**Issue by djaghah** [multiversx/mx-template-dapp#60]
Hello,

After installing the ping-pong dapp on ubuntu and following all steps... contract deployment etc, when I click Ping (after having logged in with my account) I get this error:

Sender not allowed: erd1qqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqqq6gq4hu

This contract address is in fact the contract address that manages the contract deployment. What am I missing? Have I missed some config steps?

**Comment by CiprianDraghici** [comment]
Closed due to inactivity
