### ISSUE TITLE
Source Map Parse Error during compilation on Windows

### ISSUE THREAD

**Issue by icegriffinguru** [multiversx/mx-template-dapp#78]
![image](https://user-images.githubusercontent.com/97042732/202872268-d99d3cfd-66d1-4039-b131-89857e431646.png)

**Comment by tomdgImpact** [comment]
I have the same issue on linux, did you found any walkthrough for this error @icegriffinguru ?

**Comment by icegriffinguru** [comment]
@tomdgImpact 
I have not resolved it yet. I think it's because @walletconnect and other few modules don't have typescript annotation interparts.

**Comment by CiprianDraghici** [comment]
Warnings are related to `@walletconnect ` which is not under our maintenance, but we will investigate this with lower priority as this is not a blocker
