### ISSUE TITLE
Use Bootstrap 5 & react-bootstrap 2.7

### ISSUE THREAD

**Issue by raress96** [multiversx/mx-template-dapp#87]
I want to propose to use the latest react-bootstrap (currently 2.7) which has support for Bootstrap 5.

The new version of Bootstrap has a lot of new utilities that make writing styling much easier, and IMO it should be used here as well so projects that create Dapps from this template have the latest dependencies, and not dependencies that reached end of life.

**Comment by CiprianDraghici** [comment]
Hello,

Thanks for your proposal. This is just an example of dApp. You are not forced to use bootstrap or a specific version of bootstrap. Anyone is free to use the preferred styling library (or custom styles).

**Comment by raress96** [comment]
Then I think the bootstrap and react-bootstrap dependencies should be removed, since most who create a Dapp from this template will just use the default dependencies from my experience.

**Comment by CiprianDraghici** [comment]
This is just an example of dApp, a starting point for interacting with the MultiversX blockchain. If somebody wants to use other libraries they should prepare a custom project and use this template just as a reference.
