### ISSUE TITLE
dApp only functioning properly in Incognito mode

### ISSUE THREAD

**Issue by alexisdavidson** [multiversx/mx-template-dapp#92]
This is how the page looks like when I'm starting it on normal Google Chrome:

![normal](https://user-images.githubusercontent.com/3207620/215382066-60364c6f-3b14-437f-af7b-59f896784ee3.png)

But it is working fine on Incognito mode. Any idea what the reason could be? The dApp that I'm creating myself shows a similar behavior

![incognito](https://user-images.githubusercontent.com/3207620/215382082-43871c0f-e66f-475a-8a21-c85e0e858d26.png)

**Comment by CiprianDraghici** [comment]
Did you try to clear the browser's local-storage and session-storage?

**Comment by arhtudormorar** [comment]
Hi! 
  Please upgrade to the latest sdk-dapp, or use the latest template-dapp
  Clearing localStorage and sessionStorage would resolve it, like @CiprianDraghici mentioned

**Comment by CiprianDraghici** [comment]
Closing the issue. The provided solution is working.
